### PR TITLE
fix saving per server/world prefix/suffix/display

### LINKED ISSUE #161: Prefix Dupe
Prefixes get duped/triplped when migrating from Yaml to MySql2. It adds the main group prefix to all the world prefixes causing players to have multiple prefixes in chat.

### PR DESCRIPTION
**Pull request by CodeCrafter47**
Fixes #161

### CODE REVIEW

**Comment by punnydoge** [comment]
Thank you for the heads up, CC! I derp a lot so I wasn't sure if it was me xD

**Comment by punnydoge** [comment]
Is there a build available that incorporates this fix? I tried to build from the master but I'm too noob, I think I need to add some libraries to the build path.

**Comment by CodeCrafter47** [comment]
As this is a pull request there is no build available for it. I'm currently thinking of making a build with all my PRs avaible through my jenkins.

**Comment by punnydoge** [comment]
OK, thanks a bunch for all your contributions, CC! :+1:

**Comment by CodeCrafter47** [comment]
You can not get a build with the patch from http://ci.codecrafter47.dyndns.eu/job/BungeePerms/

**Comment by punnydoge** [comment]
You, Sir, are my hero. Thank you!!!

**Comment by xion87** [comment]
dont work, i tried to 
- set 1 group
- add user to that group
- set prefix [VIP] for server HUB
- sert prefix [VIP] for server CREATIVE

Only prefix on creative server will work... in hub not

**Comment by weaondara** [comment]
where did you type in the commands?
where if your prefix using plugin?

**Comment by xion87** [comment]
i typed in game the command, actual i am using chatcontrolpro

**Comment by xion87** [comment]
it dont recognize the prefix on the hub, instead on other server it work

**Comment by weaondara** [comment]
i guess you have per server perms creative server
well i found a bug loading prefixes ...

**Comment by weaondara** [comment]
see #186

**Comment by xion87** [comment]
yep ^^

**Pull request merged**
