### PR TITLE
Fix maven structure + add jenkins profile (auto buildnumber)

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
@weaondara What do you think?

**Comment by weaondara** [comment]
i took a look but unluckily i modify the pom yesterday and today
i'll try to merge it

**Comment by sgdc3** [comment]
Yeah but why do you need a nexus server? Jenkins can do it automatically! ;)

**Comment by sgdc3** [comment]
@weaondara Any news? ;)

**Comment by aurorasmiles** [comment]
Kinda implemented already

**Pull request closed without merging**
