### PR TITLE
[WIP] fix and enable simplify permissions

### PR DESCRIPTION
**Pull request by CodeCrafter47**
I uncommented and fixes the code for simplifying permissions and added some test cases to verify it's working.

I did not enable the simplification code for regex perms as it is more difficult in that case and probably not worth the optimisation.

### CODE REVIEW

**Comment by TWSSYesterday** [comment]
@weaondara input on this? :)

**Comment by weaondara** [comment]
i'm very likely to accept this pr but i haven't got the time to review it 
please be patient ... i'll try to do it in the next few days

**Comment by CodeCrafter47** [comment]
I added simplification of regex permissions.

I'm not sure whether simplifying permission should be done at all as it may break plugins which read numbers from permissions.

**Comment by weaondara** [comment]
jep

**Comment by CodeCrafter47** [comment]
whatever that is supposed to mean...

If it breaks plugins that read numbers from permissions that could be solved by giving these plugins the unmodified permission list while using the simplified permission to speed up permission lookups.

**Comment by xaoseric** [comment]
@CodeCrafter47 hi there, if you want, you can send this push to my fork of BungeePerms https://github.com/BungeePEX/BungeePEX

**Comment by CodeCrafter47** [comment]
I'm not interested in contributing to your fork. However if you want to use the code in this PR, feel free to do so.

**Comment by weaondara** [comment]
permission simplification dropped for bp 4 due to stated reasons

**Pull request closed without merging**
